ChatApp/urls.py
from django.contrib import admin
from django.urls import path, include
from ChatApp.settings import *
from django.conf.urls.static import static
from ChatApp import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from chat.views import *
from ChatApp.settings import *

urlpatterns = [
        #nombre                 view                    url
    path('',                    inicio,             name='inicio'),
    path('nosotros/',           nosotros,           name='nosotros'),
    path("resultadosblog/",     resultadosblog,     name='resultadosblog'),
    path('form-blog/',          form_blog,          name='form_blog'),
    path('chat',                chat_view,          name='chats'),
    path('padre/',              padre_view,         name='padre'),

#Apartado de Blogs

    path('blog-del/<id>/',             blog_del,         name='blog_del'),
    path('blog-edit/<id>/',            blog_edit,        name='blog_edit'),
    path('blog-view/<id>/',            blog_view,        name='blog_view'),

#Apartado del Usuario
    path('user/',                   user,               name='user'),
    path('index',                   index,              name='index'),
    path('register',                register_view,      name='register'),
    path('MenuBlogs/',         user_MenuBlogs,     name='user_MenuBlogs'),
    path("Edit/",              user_Edit,          name="user_Edit"),
    path('EditPass/',          user_EditPass,      name='user_EditPass'),
    path('AddAvatar/',         user_AddAvatar,     name='user_AddAvatar'),
    path('MisBlogs/',          user_MisBlogs,      name='user_MisBlogs'),

#Apartado del ChatApp
    path('chat/<int:sender>/<int:receiver>',          message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>',  message_list, name='message-detail'),
    path('api/messages',                              message_list, name='message-list'),

#Logout
    path('logout/',  LogoutView.as_view(template_name='chat/logout.html'), name='logout'),
]

chat/models.py
from io import UnsupportedOperation
from django.contrib.auth.models import User
from django.db import models


class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.message
    class Meta:
        ordering = ('timestamp',)

class Blog(models.Model):
    titulo      = models.CharField(max_length=120)
    subtitulo   = models.CharField(max_length=200)
    cuerpo      = models.TextField(max_length=9000)
    autor       = models.CharField(max_length=50)
    fecha       = models.DateField()
    imagen      = models.ImageField(upload_to='media', null=True, blank=True)
    usuario     = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.titulo +""+ self.subtitulo +""+ self.autor

    def delete(self, using=None, keep_parents=False):
        self.imagen.storage.delete(self.imagen.name)
        super().delete()

class Avatar(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    imagen= models.ImageField(upload_to='avatares')
    def __str__(self):
        return self.imagen

chat/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import TextInput
from .models import Blog

#Formularios del Usuario
class SignUpForm(UserCreationForm):
    email     = forms.EmailField()
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields=['email','username','password1','password2']
        widgets = {'username': TextInput(attrs={'class':'form-control'}),}

class UserEditForm(UserCreationForm):
    first_name      =forms.CharField(label = 'Editar Nombre')
    last_name       =forms.CharField(label = 'Editar Apellido')
    email           =forms.EmailField()
    class Meta:
        model       = User
        fields      = ['email', 'first_name', 'last_name']
        help_texts  = {x:"" for x in fields}  

class UserPassEditForm(UserCreationForm):
    password1       =forms.CharField(label='Ingrese Nueva Contraseña',widget=forms.PasswordInput)
    password1       =forms.CharField(label='Ingrese Nueva Contraseña',widget=forms.PasswordInput)
    class Meta:
        model       = User
        fields      = ['password1', 'password2']
        help_texts  = {x:"" for x in fields}  

class AvatarForm(forms.Form):
    imagen          =forms.ImageField(label='Imagen')

#Formulario del Blog
class BlogForm(forms.Form):
    titulo          =forms.CharField(max_length=50)
    subtitulo       =forms.CharField(max_length=50)
    cuerpo          =forms.CharField(max_length=1000, widget      =forms.Textarea)
    autor           =forms.CharField(max_length=30)
    fecha           =forms.DateField(label='Fecha aaaa-mm-dd')
    imagen          =forms.ImageField(label='imagen')
    class Meta:
        model = Blog
        fields = ['titulo','subtitulo','cuerpo','autor','fecha','imagen',]

chat/views.py
from webbrowser import get
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http.response import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from chat.models import *
from chat.forms import *
from chat.serializers import MessageSerializer

#Views posibles para Invitado
def padre_view(request):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        return render(request, 'chat/padre.html',
            {'users': User.objects.exclude(username=request.user.username) })

def inicio(request):
    if request.user.is_authenticated:
        return render(request, "chat/inicio.html" ,{'avatar':obteneravatar(request)})
    else:
        return render(request, "chat/inicio.html")

def nosotros(request):
    if request.user.is_authenticated:
        return render(request, "chat/nosotros.html",{'avatar':obteneravatar(request)})
    else:
        return render(request, "chat/nosotros.html")

def resultadosblog(request):
    Blogs=Blog.objects.all()
    if request.user.is_authenticated:
        return render(request, "chat/resultadosblog.html",{'Blog':Blogs ,'avatar':obteneravatar(request)})
    else:
        return render(request, "chat/resultadosblog.html",{'Blog':Blogs})

#Apartado de Blogs
@login_required
def user_MenuBlogs(request):
    return render(request, "chat/user_MenuBlogs.html",{'avatar':obteneravatar(request)}) 

@login_required
def form_blog(request):
    if request.method=="POST":
        formulario=BlogForm(request.POST, request.FILES)
        if formulario.is_valid():
            info        =formulario.cleaned_data
            objeto=Blog(
            usuario     =request.user,  
            titulo      =info["titulo"],
            subtitulo   =info["subtitulo"],
            cuerpo      =info["cuerpo"],
            autor       =info['autor'],
            fecha       =info["fecha"],
            imagen      =info["imagen"],
            )
            objeto.save()
            return render(request, "chat/form_blog.html", {'usuario':request.user, 'mensaje':'Formulario Creado Exitosamente', "imagen": objeto.imagen.url,'avatar':obteneravatar(request)})
        else:
            return render(request, "chat/form_blog.html", {"mensaje":"Error",'avatar':obteneravatar(request)})
    else:
        formulario=BlogForm()
        return render (request, "chat/form_blog.html", {"formulario":formulario ,'avatar':obteneravatar(request)})

@login_required
def blog_del(request,id):
    blog=Blog.objects.get(id=id)
    blog.delete()
    Blogs=Blog.objects.filter(usuario=request.user)
    return render(request, 'chat/user_MisBlogs.html',{'Blog':Blogs ,'avatar':obteneravatar(request)})

@login_required
def blog_edit(request,id):
    blog=Blog.objects.get(id=id)
    if request.method=='POST':
        form=BlogForm(request.POST, request.FILES)
        if form.is_valid():
            info             =form.cleaned_data
            blog.titulo      =info["titulo"]
            blog.subtitulo   =info["subtitulo"]
            blog.cuerpo      =info["cuerpo"]
            blog.autor       =info['autor']
            blog.fecha       =info["fecha"]
            blog.imagen      =info["imagen"]
            blog.save()
            Blogs=Blog.objects.all()
            return render(request, 'chat/blog_edit.html',{'blog':blog,"imagen": blog.imagen.url,'Blogs':Blogs,'mensaje':"Blog Editado Exitosamente"})
        else:
            Blogs=Blog.objects.all()
            return render(request, 'chat/blog_edit.html',{'blog':blog,"imagen": blog.imagen.url,'Blogs':Blogs,'mensaje':"Faltan Campos por rellenar o Formulario Invalido"})
    else:
        form=BlogForm(initial={'titulo':blog.titulo,'subtitulo':blog.subtitulo,'cuerpo':blog.cuerpo,'autor':blog.autor,'fecha':blog.fecha,'imagen':blog.imagen.url})
        return render(request, 'chat/blog_edit.html',{'formulario':form, 'blog':blog})

def blog_view(request,id):
    blog=Blog.objects.filter(id=id)
    if request.user.is_authenticated:
        return render(request, "chat/blog_view.html",{'Blog':blog ,'avatar':obteneravatar(request)})
    else:
        return render(request, "chat/blog_view.html",{'Blog':blog})



#Registro
def register_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            email    = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password, email=email)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('inicio')
        else:
            return render(request, 'chat/register.html',{'form':form, 'mensaje':"Formulario Invalido, verifique los datos"})
    else:
        form = SignUpForm()
        template = 'chat/register.html'
        context = {'form':form}
        return render(request, template, context)

#Login
def index(request):
    if request.user.is_authenticated:
        return redirect('inicio')
    elif request.method == "POST":
        username, password = request.POST['username'], request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('inicio')
        else:
            return render(request, 'chat/index.html',{'mensaje':'EL NOMBRE DE USUARIO O CONTRASEÑA SON INVALIDOS'})
    else:
        return render(request, 'chat/index.html')

#Apartado del Usuario
@login_required
def user_AddAvatar(request):
    if request.method=='POST':
        formulario          =AvatarForm(request.POST, request.FILES)
        if formulario.is_valid():
            avatarViejo     = Avatar.objects.filter(user=request.user)
            if(len(avatarViejo)>0):
                avatarViejo[0].delete()
            avatar  =Avatar (   user=request.user, 
                                imagen=formulario.cleaned_data['imagen'])
            avatar.save()
            return render(request, 'chat/inicio.html', {'usuario':request.user, 'mensaje':'Avatar Agregado Exitosamente', "avatar": avatar.imagen.url})
        else:
            return render(request, 'chat/user_AddAvatar.html', {'formulario':formulario, 'mensaje':'FORMULARIO INVALIDO'})
    else:
        formulario=AvatarForm()
        return render(request, "chat/user_AddAvatar.html", {"formulario":formulario, "usuario":request.user, "avatar": obteneravatar(request)})

def obteneravatar(request):
    lista=Avatar.objects.filter(user=request.user)
    if len(lista)!=0:
        imagen=lista[0].imagen.url
    else:
        imagen="media/avatares/avatarpordefecto.png"
    return imagen

@login_required
def user(request):
    return render(request, "chat/user.html",{'avatar':obteneravatar(request)}) 

@login_required
def user_MisBlogs(request):
    Blogs=Blog.objects.filter(usuario=request.user)
    return render(request, 'chat/user_MisBlogs.html',{'Blog':Blogs ,'avatar':obteneravatar(request)})

@login_required
def user_Edit(request):
    usuario=request.user
    if request.method=="POST":
        form=UserEditForm(request.POST)
        if form.is_valid():
            info=form.cleaned_data
            usuario.first_name  =info["first_name"]
            usuario.last_name   =info["last_name"]
            usuario.email       =info["email"]
            usuario.save()
            return render(request, "chat/inicio.html", {"mensaje":"Perfil Editado Exitosamente",'avatar':obteneravatar(request)})
        else:
            return render(request, "chat/user_Edit.html", {"formulario":form, "usuario":usuario, "mensaje":"FORMULARIO INVALIDO",'avatar':obteneravatar(request) })
    else:
        form= UserEditForm(initial={'first_name':usuario.first_name,'last_name':usuario.last_name,'email':usuario.email})
        return render(request, "chat/user_Edit.html", {"formulario":form, "usuario":usuario,'avatar':obteneravatar(request)})

@login_required
def user_EditPass(request):
    usuario=request.user
    if request.method=="POST":
        form=UserPassEditForm(request.POST)
        if form.is_valid():
            info=form.cleaned_data
            usuario.password   =info["password1"]
            usuario.password2   =info["password2"]
            usuario.save()
            return render(request, "chat/inicio.html", {"mensaje":"Perfil Editado Exitosamente",'avatar':obteneravatar(request)})
        else:
            return render(request, "chat/user_EditPass.html", {"formulario":form, "usuario":usuario, "mensaje":"FORMULARIO INVALIDO",'avatar':obteneravatar(request)})
    else:
        form= UserPassEditForm(instance=usuario)
        return render(request, "chat/user_EditPass.html", {"formulario":form, "usuario":usuario,'avatar':obteneravatar(request)})

#Aplicacion de Chat
@csrf_exempt
def message_list(request, sender=None, receiver=None):
    """
    List all required messages, or create a new message.
    """
    if request.method == 'GET':
        messages = Message.objects.filter(sender_id=sender, receiver_id=receiver, is_read=False)
        serializer = MessageSerializer(messages, many=True, context={'request': request})
        for message in messages:
            message.is_read = True
            message.save()
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = MessageSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)

templates/chat/blog_edit.html
{% extends "chat/padre.html" %}

{% load static %}

{% block titulo %}
<h1 class="mb-5" >  </h1>
{% endblock %}

{% block contenido_que_cambia %}
<div>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'form_blog' %}">Crear Blog</a>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'user_MisBlogs' %}">Mis Blogs</a>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'resultadosblog' %}">Todos los Blogs</a>
</div>
<h1>Modifica tu blog aqui!</h1>
{{ mensaje }}

<form action="{% url 'blog_edit' blog.id %}" method="POST" enctype="multipart/form-data"> {% csrf_token %}

    <table>
        {{ formulario.as_table }}
    </table>
    <input class="btn btn-info" type="submit" value="Crear">

</form> 
{% endblock%}

templates/chat/blog_view.html
{% extends "chat/padre.html" %}
{% load static %}

{% block titulo %}
<h1 class="mb-5">Blog </h1>
{% endblock %}

{% block contenido_que_cambia %}
{% if user.is_authenticated %}
<div>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'form_blog' %}">Crear Blog</a>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'user_MisBlogs' %}">Mis Blogs</a>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'resultadosblog' %}">Todos los Blogs</a>
</div>
{% endif %}
{% if Blog %}

    {% for bl in Blog %}
        <div>
            <img    src="{{ bl.imagen.url }}" height="300" alt="imagen del blog"></img>
            <h1>    {{ bl.titulo }}</h1>
        </div>
        <div>
            <h2>    {{ bl.subtitulo }}</h2>
            <h2>    {{ bl.autor }}</h2>
            <h3>    {{ bl.fecha }}</h3>
        </div>
        <div>
            <h5>    {{ bl.cuerpo }}</h5> 
        </div>
    {% endfor %}

{% else %}
<p>No se han encontrado Blogs</p>

{% endif %}

{% endblock %}

templates/chat/chat.html
{% extends 'chat/index.html' %}
{% block body %}
<nav class="blue lighten-3">
    <div class="nav-wrapper container">
    <a class="brand-logo">ChatApp {{ user.username }}</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="{% url 'user' %}">{{ request.user.first_name }}</a></li>
        <li><a class="btn btn-primary " href="{% url 'inicio' %}">Inicio</a></li>
        <li><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
    </ul>
    </div>
</nav>
    <div class="section" style="height: 80vh">
    <div class="row">
        <div class="col s3">
        <div class="card">
            <div class="collection">
                {% for user in users %}
                <a href="{% url 'chat' request.user.id user.id %}" id="user{{ user.id }}" class="collection-item row">
                    <img src="media/avatares/avatarpordefecto.png" width="30" height="30" />
                    <div class="col s8">
                    <span class="title" style="font-weight: bolder">{{ user.username }}</span>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
        </div>
        <div class="col s9">
            <div class="card">
            <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll">
                {% block messages %}

                {% endblock %}
            </div>
            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <input id="id_message" name="message" type="text" placeholder="Type your message..">
                        </div>
                    </div>
                    <div class="col s1" style="line-height: 80px">
                        <button class="btn btn-floating blue lighten-2 waves-effect waves-light"><i class="material-icons">send</i></button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    </div>
    {% load staticfiles %}
    <script src="{% static 'js/chat.js' %}"></script>
    <script>
        // For receiving
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
                message.val('');
            })
        })
    </script>
{% endblock %}

templates/chat/form_blog.html
{% extends "chat/padre.html" %}

{% load static %}

{% block titulo %}
<h1 class="mb-5" >Escribe tu Blog </h1>
{% endblock %}

{% block contenido_que_cambia %}
<div>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'form_blog' %}">Crear Blog</a>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'user_MisBlogs' %}">Mis Blogs</a>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'resultadosblog' %}">Todos los Blogs</a>
</div>
<h1>¿Escribi tu blog aqui!</h1>
{{ mensaje }}
<form action="{% url 'form_blog' %}" method="POST" enctype="multipart/form-data"> {% csrf_token %}
    <table>
        {{ formulario.as_table }}
    </table>
    <input class="btn btn-info" type="submit" value="Crear">
    
</form>
{% endblock%}

templates/chat/index.html
{% load staticfiles %}
  <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
    </head>

    <body>
    {% block body %}
        <div class="section blue lighten-3">
            <div class="container white-text center-align text">
            <h2>Entrega Final CoderHouse</h2>
            <h3>{{ mensaje }}</h3>
            </div>
        </div>
        <div class="container">
            <div class="row">
            <div class="col s12 m8 l6 offset-m2 offset-l3">
                <div class="section center-block">
                <div>
                    {% block form %}
                    <h3>
                    Login
                    </h3>
                    <form id="login-form" class="form-group" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="username" id="id_username" type="text">
                                <label for="id_username">Username</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="password" id="id_password" type="password">
                                <label for="id_password">Password</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s8">
                                <a href="{% url 'register' %}">Register</a>
                            </div>
                            <div class="col s4">
                            <div class="right">
                                <button class="btn blue waves-effect waves-light pull-s12">Login</button>
                            </div>
                            </div>
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
            </div>
            </div>
        </div>
        {% endblock %}
    </body>

  </html>

templates/chat/logout.html
{% extends "chat/padre.html" %}

{% load static %}

{% block titulo %}
<h1 class="mb-5">LOGOUT</h1>
{% endblock %}

{% block contenido_que_cambia %}
<h1>TE DESLOGUEASTE CORRECTAMENTE </h1>
{% endblock %}

templates/chat/messages.html
{% extends 'chat/chat.html' %}
{% block hide %}{% endblock %}
{% block messages %}
    {% for message in messages %}
    {% if message.sender == request.user %}
<div class="card-panel right" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">You</div>
    {{ message }}
</div>
    {% else %}
<div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ message.sender }}</div>
    {{ message }}
</div>
    {% endif %}
    {% endfor %}
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,1000)
})
</script>
{% endblock %}

templates/chat/register.html
{% extends 'chat/index.html' %}
{% block form %}
    <h3>
    Register
    </h3>
    <form id="register-form" class="form-group" method="POST">
        {% csrf_token %}
        {{ mensaje }}
            <div class="row">
                <div class="input-field col s12">
                    {{ form.username }}
                    <label for="id_username" data-error="Username already taken">Username</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.email }}
                    <label for="id_email" data-error="Email already taken">Email</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.password1 }}
                    <label for="id_password">Password</label>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    {{ form.password2 }}
                    <label for="id_password2">Repeat Password</label>
                </div>
            </div>
            <div class="row">
                <div class="col s12">
                    <a href="{% url 'inicio' %}">Invitado </a> 
                <div class="right">
                    <a href="{% url 'index' %}">Login </a> 
                    <button class="btn blue waves-effect waves-light pull-s12">Register</button>
                </div>
                </div>
            </div>
    </form>
{% endblock %}

templates/chat/resultadosblog.html
{% extends "chat/padre.html" %}

{% load static %}

{% block titulo %}
<h1 class="mb-5">RESULTADOS DE LA BUSQUEDA</h1>
{% endblock %}

{% block contenido_que_cambia %}
<h1>BUSQUEDA DE blogs</h1>
{% if blog %}

<div style="text-align: center; font-family: 'Lato', sans-serif; background-color: rgb(172, 162, 162);">
<ul>
    {% for bl in blog %}
    <h2> Titulo : " {{bl.titulo}} "  </h2>
    <h3> Autor: {{bl.autor}}</h3>
    __________________________________

    <h5 style= "background-color: rgb(201, 197, 197);" >{{bl.cuerpo}}</h5>
    <h4>Fecha: {{bl.fecha}}</h4>
    <hr>
    <br>
    -----------------------------------
    <h5> Coderhouse 2022</h5>
    -----------------------------------
        <br>
        
            <hr style= "color: rgb(0, 0, 0);">

            <img src= "/media/blanco.jpg" alt="imagen temporal" height="300"> 
        <br>

    {% endfor %}


</ul>
</div>

{% else %}
<p>NO SE ENCONTRARON blogs</p>

{% endif %}

{% endblock %}

templates/chat/user.html
{% extends "chat/padre.html" %}
{% load static %}

{% block titulo %}
<h1 class="mb-5">Perfil</h1>
{% endblock %}

{% block contenido_que_cambia %}
<div>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'user_AddAvatar' %}">Agregar/Cambiar Avatar</a>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'user_Edit' %}">Editar Usuario</a>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'user_EditPass' %}">Cambiar Contraseña</a>
</div>
<div>
    <table>
        <tr>
            <td><img src="{{ avatar }}" height="400" alt=""></td>
        </tr>
        <tr style="text-align: right ;">
            <h3>Username:    {{ user.username }}</h3>
            <h3>Nombre:      {{ user.first_name }}</h3>
            <h3>Apellido:    {{ user.last_name }}</h3>
            <h3>Email:       {{ user.email }}</h3>
        </tr>
    </table>
</div>



{% endblock%}

templates/chat/user_AddAvatar.html
{% extends "chat/padre.html" %}

{% load static %}

{% block titulo %}
<h1 class="mb-5">Agregando Avatar de {{ usuario }}</h1>
{% endblock %}

{% block contenido_que_cambia %}
<div>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'user_AddAvatar' %}">Agregar/Cambiar Avatar</a>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'user_Edit' %}">Editar Usuario</a>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'user_EditPass' %}">Cambiar Contraseña</a>
</div>
<h1>Agregar Avatar</h1>
<form action="{% url 'user_AddAvatar' %}" method="POST" enctype="multipart/form-data"> {% csrf_token %}

    <table>
        {{ formulario.as_table }}
    </table>
    <button type="submit">Agregar Avatar</button>
</form>
{% endblock %}

templates/chat/user_Edit.html
{% extends "chat/padre.html" %}

{% load static %}

{% block titulo %}
<h1 class="mb-5">Editar Perfil de {{ user }}</h1>
{% endblock %}

{% block contenido_que_cambia %}
<div>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'user_AddAvatar' %}">Agregar/Cambiar Avatar</a>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'user_Edit' %}">Editar Usuario</a>
    <a class="btn btn-primary" style="color: lightblue;" href="{% url 'user_EditPass' %}">Cambiar Contraseña</a>
</div>
<h2>Formulario Datos de Usuario</h2>
<h3>{{ mensaje }}</h3>
<form action="{% url 'user_Edit' %}" method="POST"> {% csrf_token %}

    <table>
        {{ formulario.as_table }}
    </table>
    <input type="submit" value="guardar">

</form>


{% endblock %}